pipeline:
  name: p-3
  identifier: p3
  projectIdentifier: satendrap1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: c-1
        identifier: c1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
