pipeline:
  name: pipeline-3790
  identifier: pipeline3790
  projectIdentifier: dlp1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: c-1
        identifier: c1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: service10
            serviceDefinition:
              spec: {}
              type: Kubernetes
          infrastructure:
            environmentRef: env2
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: dlk8scluster1
                namespace: sk
                releaseName: release-<+INFRA_KEY_SHORT_ID>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
